export const CHANGE_HOLIDAY_LABEL = {
  TITLE: "Change Holiday",
  CREATE_TITLE: "Add Change Holiday",
  EDIT_TITLE: "Edit Change Holiday",
  TARGET_TYPE: "Apply To",
  TARGET: "Target",
  TARGET_EMPLOYEE: "Per Employee",
  TARGET_PAYROLL_GROUP: "Per Payroll Group",
  TARGET_EMPLOYEE_GROUP: "Group of Employees",
  EMPLOYEE: "Employee",
  EMPLOYEE_GROUP: "Employees",
  PAYROLL_GROUP: "Payroll Group",
  HOLIDAY_NAME: "Holiday Name",
  HOLIDAY: "Holiday",
  CLIENT: "Client",
  FROM_DATE: "Payroll Date From",
  TO_DATE: "Payroll Date To",
  REPLACEMENT_DATE: "Replacement Date",
  // Filters
  FILTER_EMPLOYEE: "Employee",
  FILTER_FROM_DATE: "Date From",
  FILTER_TO_DATE: "Date To",
};
