export const TARDINESS_LABEL = {
  TITLE: "Tardiness Report",
  DATE: "Date",
  EMPLOYEE_ID: "Employee ID",
  EMPLOYEE_NAME: "Name",
  DEPARTMENT: "Department",
  SCHEDULED_IN: "Scheduled In",
  ACTUAL_IN: "Actual In",
  GRACE_PERIOD: "Grace Period",
  TARDINESS_MINS: "Tardiness (Mins)",
  DEDUCTIBLE: "Deductible",
  FILTER_DEPARTMENT: "Department",
  FILTER_EMPLOYEE: "Employee",
  FILTER_PAYROLL_GROUP: "Payroll Group",
};
