export const FLEXI_TIME_SHIFT_LABEL = {
  TITLE: "Flexi Time Shift",
  SHIFT_NAME: "Shift Name",
  START_TIME: "Earliest Clock-In Time",
  END_TIME: "Latest Clock-Out Time",
  MIN_WORKING: "Minimum Working Time (hrs)",
  MAX_WORKING: "Maximum Working Time (hrs)",
  UNPAID_LUNCH_BREAK: "Set Allowable Break Window",
  BREAK_PERIOD_START: "Allowable Break Period Start",
  BREAK_PERIOD_END: "Allowable Break Period End",
  BREAK_DURATION: "Break Duration (min)",
  ALLOW_OT: "Allow Overtime",
  OT_THRESHOLD: "OT Threshold (hrs)",
  MAX_OT_HOURS: "Max OT Hours",
  CREATE_TITLE: "Create Flexi Time Shift",
  EDIT_TITLE: "Edit Flexi Time Shift",
};
