export const FLEXI_TIME_SHIFT_LABEL = {
  TITLE: "Flexi Time Shift",
  SHIFT_NAME: "Shift Name",
  START_TIME: "Earliest Clock-In Time",
  END_TIME: "Latest Clock-Out Time",
  MIN_WORKING: "Minimum Working Time (min)",
  MAX_WORKING: "Maximum Working Time (min)",
  UNPAID_LUNCH_BREAK: "Unpaid Lunch Break",
  LUNCH_START: "Lunch Start",
  LUNCH_END: "Lunch End",
  BREAK_DURATION: "Break Duration (min)",
  ALLOW_OT: "Allow Overtime",
  OT_THRESHOLD: "OT Threshold (min)",
  CREATE_TITLE: "Create Flexi Time Shift",
  EDIT_TITLE: "Edit Flexi Time Shift",
};
