export const FIXED_TIME_SHIFT_LABEL = {
  TITLE: "Fixed Time Shift",
  SHIFT_NAME: "Shift Name",
  START_TIME: "Start Time",
  END_TIME: "End Time",
  GRACE_PERIOD: "Grace Period (min)",
  LUNCH_BREAK_MODE: "Lunch Break",
  LUNCH_START: "Lunch Start",
  LUNCH_END: "Lunch End",
  BREAK_DURATION: "Break Duration (min)",
  AM_BREAK: "AM Break",
  AM_START: "AM Break Start",
  AM_END: "AM Break End",
  PM_BREAK: "PM Break",
  PM_START: "PM Break Start",
  PM_END: "PM Break End",
  MAX_WORKING: "Max Working Time (min)",
  MIN_WORKING: "Min Working Time (min)",
  ALLOW_OT: "Allow Overtime",
  OT_REQUIRE_TIME_IN: "Require Time-In for OT",
  OT_START: "OT Start Time",
  OT_THRESHOLD: "OT Threshold (min)",
  MAX_OT_HOURS: "Max OT Hours",
  CREATE_TITLE: "Create Fixed Time Shift",
  EDIT_TITLE: "Edit Fixed Time Shift",
};
