export const FOR_PAYROLL_LABEL = {
  TITLE: "For Payroll",
  BIO_ID: "BioId",
  EMPLOYEE: "Employee",
  LATE: "Late",
  UNDER_TIME: "Under Time",
  REG_NET: "Reg. Net",
  NET_OVERTIME: "Net Overtime",
  ND: "ND",
  ND_OT: "ND OT",
  REST_DAY_NET: "Rest Day Net",
  REST_DAY_OT: "Rest Day OT",
  RD_ND: "RD ND",
  RD_ND_OT: "RD ND OT",
  LH: "LH",
  LH_OT: "LH OT",
  LH_ND: "LH ND",
  LH_ND_OT: "LH ND OT",
  SPH: "SPH",
  SPH_OT: "SPH OT",
  SPH_ND: "SPH ND",
  SPH_ND_OT: "SPH ND OT",
  FILTER_FROM_DATE: "From",
  FILTER_TO_DATE: "To",
  FILTER_DEPARTMENT: "Department",
  FILTER_CLIENT: "Client",
  FILTER_EMPLOYEE: "Employee",
  FILTER_PAYROLL_GROUP: "Payroll Group",
};
