import dayjs from "dayjs";
import type { PayrollRunResult } from "../../../models/api/response/payroll-run-result.model";
import {
  otPay,
  ndPay,
  basicPay,
  holidayPay,
} from "../../../utils/ot-nd-pay.util";
import {
  fmt,
  holidayDuty,
  restLegalTotal,
  specialTotal,
  restSpecialTotal,
  doubleLegalTotal,
  restDoubleLegalTotal,
  restDayTotal,
} from "./payroll-summary.util";

// CSV/Excel export builders for the Payroll Summary page — one function/header pair per sheet,
// mirroring each tab's own columns (see ../columns/*) so "1 tab on screen, 1 sheet in Excel."

export const EXPORT_HEADERS = [
  "Employee",
  "Period Start",
  "Period End",
  "Salary Type",
  "Daily Rate",
  "Basic",
  "OT Pay",
  "OT Premium",
  "ND Pay",
  "ND Premium",
  "ND-OT Pay",
  "Rest Day",
  "Paid Leave",
  "1x Payout (Company)",
  "1x Payout (Government)",
  "Legal Holiday (Unworked)",
  "Legal Holiday Duty (Worked)",
  "Rest Day + Legal Holiday",
  "Special Holiday",
  "Rest Day + Special Holiday",
  "Double Legal Holiday",
  "Rest Day + Double Legal Holiday",
  "Holiday Total",
  "COLA",
  "Allowances",
  "Bonuses",
  "Commissions",
  "De Minimis",
  "Other Income",
  "Reimbursement",
  "Gross Income",
  "SSS",
  "PhilHealth",
  "Pag-IBIG",
  "W-Tax",
  "Loans",
  "Other Deductions",
  "Late",
  "Under Time",
  "Absent",
  "Total Deductions",
  "Net Pay",
  "ER SSS",
  "ER PhilHealth",
  "ER Pag-IBIG",
  "EC",
  "Total ER Cost",
  "Regular Hrs",
  "Reg OT Hrs",
  "Reg ND Hrs",
  "Reg ND-OT Hrs",
  "Rest Day Hrs",
  "RD OT Hrs",
  "RD ND Hrs",
  "RD ND-OT Hrs",
  "Legal Hol Hrs",
  "Legal OT Hrs",
  "Legal ND Hrs",
  "Legal ND-OT Hrs",
  "Special Hol Hrs",
  "Special OT Hrs",
  "Special ND Hrs",
  "Special ND-OT Hrs",
  "RD+Legal Hrs",
  "RD+Legal OT Hrs",
  "RD+Legal ND Hrs",
  "RD+Legal ND-OT Hrs",
  "RD+Special Hrs",
  "RD+Special OT Hrs",
  "RD+Special ND Hrs",
  "RD+Special ND-OT Hrs",
  "Double Legal Hrs",
  "Double Legal OT Hrs",
  "Double Legal ND Hrs",
  "Double Legal ND-OT Hrs",
  "RD+Double Legal Hrs",
  "RD+Double Legal OT Hrs",
  "RD+Double Legal ND Hrs",
  "RD+Double Legal ND-OT Hrs",
  "OB Hrs",
  "Paid Leave Hrs",
  "Unpaid Leave Hrs",
  "OT Total Hrs",
  "Retirement Accrual",
  "RD ND Base",
  "RD ND Premium",
  "RD ND-OT Base",
  "RD OT Base",
  "RD ND-OT Premium",
  "Legal ND Base",
  "Legal ND Premium",
  "Legal ND-OT Base",
  "Legal OT Base",
  "Legal ND-OT Premium",
  "Special ND Base",
  "Special ND Premium",
  "Special ND-OT Base",
  "Special OT Base",
  "Special ND-OT Premium",
  "RD+Legal ND Base",
  "RD+Legal ND Premium",
  "RD+Legal ND-OT Base",
  "RD+Legal OT Base",
  "RD+Legal ND-OT Premium",
  "RD+Special ND Base",
  "RD+Special ND Premium",
  "RD+Special ND-OT Base",
  "RD+Special OT Base",
  "RD+Special ND-OT Premium",
  "Double Legal ND Base",
  "Double Legal ND Premium",
  "Double Legal ND-OT Base",
  "Double Legal OT Base",
  "Double Legal ND-OT Premium",
  "RD+Double Legal ND Base",
  "RD+Double Legal ND Premium",
  "RD+Double Legal ND-OT Base",
  "RD+Double Legal OT Base",
  "RD+Double Legal ND-OT Premium",
];

export const buildExportRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    r.payPeriodStart ? dayjs(r.payPeriodStart).format("YYYY-MM-DD") : "",
    r.payPeriodEnd ? dayjs(r.payPeriodEnd).format("YYYY-MM-DD") : "",
    r.salaryType,
    fmt(r.dailyRate),
    fmt(r.basicPay),
    // OT Pay/ND Pay fold in NDOT's Additive-mode top-up (see ot-nd-pay.util.ts); OT
    // Premium/ND Premium/ND-OT Pay stay raw/unfolded — granular audit detail, not a summary.
    fmt(otPay(r)),
    fmt(r.otPremiumPay ?? 0),
    fmt(ndPay(r)),
    fmt(r.ndPremiumPay ?? 0),
    fmt(r.nightDifferentialOTPay),
    fmt(restDayTotal(r)),
    r.salaryType === "FIXED"
      ? fmt(r.nonCompanyPaidLeaves ?? 0)
      : fmt(r.paidLeaves ?? 0),
    fmt(r.companyFundedLeavePay ?? 0),
    fmt(r.governmentFundedLeavePay ?? 0),
    fmt(r.legalHolidayUnworkedPay ?? 0),
    fmt(holidayDuty(r)),
    fmt(restLegalTotal(r)),
    fmt(specialTotal(r)),
    fmt(restSpecialTotal(r)),
    fmt(doubleLegalTotal(r)),
    fmt(restDoubleLegalTotal(r)),
    fmt(r.holidayPay),
    fmt(r.cola),
    fmt(r.totalRegularAllowances),
    fmt(r.totalBonuses),
    fmt(r.totalCommissions),
    fmt(r.totalDeminimises),
    fmt(r.totalOtherIncome),
    fmt(r.reimbursement),
    fmt(r.grossIncome),
    fmt(r.sssContribution),
    fmt(r.philHealthContribution),
    fmt(r.pagIbigContribution),
    fmt(r.withholdingTax),
    fmt(r.totalLoans),
    fmt(r.otherDeductions - r.totalLoans),
    fmt(r.lateAmount),
    fmt(r.underTimeAmount),
    fmt(r.absences),
    fmt(r.totalDeductions),
    fmt(r.netPay),
    fmt(r.employerSSSContribution),
    fmt(r.employerPhilHealthContribution),
    fmt(r.employerPagIbigContribution),
    fmt(r.employerECContribution),
    fmt(
      r.employerSSSContribution +
        r.employerPhilHealthContribution +
        r.employerPagIbigContribution +
        r.employerECContribution,
    ),
    fmt(r.regularNetHours ?? 0),
    fmt(r.regularOTHours ?? 0),
    fmt(r.regularNDHours ?? 0),
    fmt(r.regularNDOTHours ?? 0),
    fmt(r.restDayHours ?? 0),
    fmt(r.restDayOTHours ?? 0),
    fmt(r.restDayNDHours ?? 0),
    fmt(r.restDayNDOTHours ?? 0),
    fmt(r.legalHolHours ?? 0),
    fmt(r.legalHolOTHours ?? 0),
    fmt(r.legalHolNightDiffHours ?? 0),
    fmt(r.legalHolNightDiffOTHours ?? 0),
    fmt(r.specialHolHours ?? 0),
    fmt(r.specialHolOTHours ?? 0),
    fmt(r.specialHolNightDiffHours ?? 0),
    fmt(r.specialHolNightDiffOTHours ?? 0),
    fmt(r.restLegalDayHours ?? 0),
    fmt(r.restLegalDayOTHours ?? 0),
    fmt(r.restLegalDayNDHours ?? 0),
    fmt(r.restLegalDayNDOTHours ?? 0),
    fmt(r.restSpecialDayHours ?? 0),
    fmt(r.restSpecialDayOTHours ?? 0),
    fmt(r.restSpecialDayNDHours ?? 0),
    fmt(r.restSpecialDayNDOTHours ?? 0),
    fmt(r.doubleLegalHours ?? 0),
    fmt(r.doubleLegalOTHours ?? 0),
    fmt(r.doubleLegalNDHours ?? 0),
    fmt(r.doubleLegalNDOTHours ?? 0),
    fmt(r.restDoubleLegalHours ?? 0),
    fmt(r.restDoubleLegalOTHours ?? 0),
    fmt(r.restDoubleLegalNDHours ?? 0),
    fmt(r.restDoubleLegalNDOTHours ?? 0),
    fmt(r.obHours ?? 0),
    fmt(r.paidLeaveHours ?? 0),
    fmt(r.unpaidLeaveHours ?? 0),
    fmt(r.overtimeHours ?? 0),
    fmt(r.retirementAccrual ?? 0), // was missing a value for the "Retirement Accrual" header
    fmt(r.restDayNDBasePay ?? 0),
    fmt(r.restDayNDPremiumPay ?? 0),
    fmt(r.restDayNDOTBasePay ?? 0),
    fmt(r.restDayOTBasePay ?? 0),
    fmt(r.restDayNDOTPremiumPay ?? 0),
    fmt(r.legalNDBasePay ?? 0),
    fmt(r.legalNDPremiumPay ?? 0),
    fmt(r.legalNDOTBasePay ?? 0),
    fmt(r.legalOTBasePay ?? 0),
    fmt(r.legalNDOTPremiumPay ?? 0),
    fmt(r.specialNDBasePay ?? 0),
    fmt(r.specialNDPremiumPay ?? 0),
    fmt(r.specialNDOTBasePay ?? 0),
    fmt(r.specialOTBasePay ?? 0),
    fmt(r.specialNDOTPremiumPay ?? 0),
    fmt(r.restLegalNDBasePay ?? 0),
    fmt(r.restLegalNDPremiumPay ?? 0),
    fmt(r.restLegalNDOTBasePay ?? 0),
    fmt(r.restLegalOTBasePay ?? 0),
    fmt(r.restLegalNDOTPremiumPay ?? 0),
    fmt(r.restSpecialNDBasePay ?? 0),
    fmt(r.restSpecialNDPremiumPay ?? 0),
    fmt(r.restSpecialNDOTBasePay ?? 0),
    fmt(r.restSpecialOTBasePay ?? 0),
    fmt(r.restSpecialNDOTPremiumPay ?? 0),
    fmt(r.doubleLegalNDBasePay ?? 0),
    fmt(r.doubleLegalNDPremiumPay ?? 0),
    fmt(r.doubleLegalNDOTBasePay ?? 0),
    fmt(r.doubleLegalOTBasePay ?? 0),
    fmt(r.doubleLegalNDOTPremiumPay ?? 0),
    fmt(r.restDoubleLegalNDBasePay ?? 0),
    fmt(r.restDoubleLegalNDPremiumPay ?? 0),
    fmt(r.restDoubleLegalNDOTBasePay ?? 0),
    fmt(r.restDoubleLegalOTBasePay ?? 0),
    fmt(r.restDoubleLegalNDOTPremiumPay ?? 0),
  ]);

export const EARNINGS_HEADERS = [
  "Employee",
  "Status",
  "Salary Type",
  "Daily Rate",
  "Period Start",
  "Period End",
  "Basic",
  "OT Pay",
  "ND Pay",
  "Rest Day",
  "Paid Leave",
  "1x Payout (Co)",
  "1x Payout (Gov)",
  "Holiday Total",
  "COLA",
  "Allowances",
  "Bonuses",
  "Commissions",
  "De Minimis",
  "Other Income",
  "Reimbursement",
  "Gross",
  "Retirement Accrual",
];
export const buildEarningsRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    r.id ? (r.isPosted ? "Posted" : "Draft") : "",
    r.salaryType === "FIXED" ? "Fixed" : "Variable",
    fmt(r.dailyRate),
    r.payPeriodStart ? dayjs(r.payPeriodStart).format("YYYY-MM-DD") : "",
    r.payPeriodEnd ? dayjs(r.payPeriodEnd).format("YYYY-MM-DD") : "",
    fmt(basicPay(r)),
    fmt(otPay(r)),
    fmt(ndPay(r)),
    fmt(restDayTotal(r)),
    r.salaryType === "FIXED"
      ? fmt(r.nonCompanyPaidLeaves ?? 0)
      : fmt(r.paidLeaves ?? 0),
    fmt(r.companyFundedLeavePay ?? 0),
    fmt(r.governmentFundedLeavePay ?? 0),
    fmt(holidayPay(r)),
    fmt(r.cola),
    fmt(r.totalRegularAllowances),
    fmt(r.totalBonuses),
    fmt(r.totalCommissions),
    fmt(r.totalDeminimises),
    fmt(r.totalOtherIncome),
    fmt(r.reimbursement),
    fmt(r.grossIncome),
    fmt(r.retirementAccrual ?? 0),
  ]);

export const HOLIDAY_HEADERS = [
  "Employee",
  "Legal Holiday (Unworked)",
  "Legal Holiday Duty (Worked)",
  "Rest Day + Legal Holiday",
  "Special Holiday",
  "Rest Day + Special Holiday",
  "Double Legal Holiday",
  "Rest Day + Double Legal Holiday",
  "Holiday Total",
];
export const buildHolidayRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    fmt(r.legalHolidayUnworkedPay ?? 0),
    fmt(holidayDuty(r)),
    fmt(restLegalTotal(r)),
    fmt(specialTotal(r)),
    fmt(restSpecialTotal(r)),
    fmt(doubleLegalTotal(r)),
    fmt(restDoubleLegalTotal(r)),
    fmt(r.holidayPay),
  ]);

export const DEDUCTIONS_HEADERS = [
  "Employee",
  "SSS",
  "PhilHealth",
  "Pag-IBIG",
  "W-Tax",
  "Cash Bond",
  "Loans",
  "Other Deductions",
  "Late/UT",
  "Absent",
  "Net Pay",
];
export const buildDeductionsRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    fmt(r.sssContribution),
    fmt(r.philHealthContribution),
    fmt(r.pagIbigContribution),
    fmt(r.withholdingTax),
    fmt(r.cashBondDeduction),
    fmt(r.totalLoans),
    fmt(r.otherDeductions - r.totalLoans),
    fmt(r.lateAmount + r.underTimeAmount),
    fmt(r.absences),
    fmt(r.netPay),
  ]);

export const ER_HEADERS = [
  "Employee",
  "ER SSS",
  "ER PhilHealth",
  "ER Pag-IBIG",
  "EC",
  "Total ER Cost",
];
export const buildErRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    fmt(r.employerSSSContribution),
    fmt(r.employerPhilHealthContribution),
    fmt(r.employerPagIbigContribution),
    fmt(r.employerECContribution),
    fmt(
      r.employerSSSContribution +
        r.employerPhilHealthContribution +
        r.employerPagIbigContribution +
        r.employerECContribution,
    ),
  ]);

export const HOURS_HEADERS = [
  "Employee",
  "Regular",
  "Reg OT",
  "Reg ND",
  "Reg ND-OT",
  "Rest Day",
  "RD OT",
  "RD ND",
  "RD ND-OT",
  "Legal Hol",
  "Legal OT",
  "Legal ND",
  "Legal ND-OT",
  "Special Hol",
  "Special OT",
  "Special ND",
  "Special ND-OT",
  "RD+Legal",
  "RD+Legal OT",
  "RD+Legal ND",
  "RD+Legal ND-OT",
  "RD+Special",
  "RD+Special OT",
  "RD+Special ND",
  "RD+Special ND-OT",
  "Double Legal",
  "Double Legal OT",
  "Double Legal ND",
  "Double Legal ND-OT",
  "RD+Double Legal",
  "RD+Double Legal OT",
  "RD+Double Legal ND",
  "RD+Double Legal ND-OT",
  "OB Hrs",
  "Paid Leave Hrs",
  "Unpaid Leave Hrs",
  "OT Total Hr",
];
export const buildHoursRows = (results: PayrollRunResult[]) =>
  results.map((r) => [
    r.fullName,
    fmt(r.regularNetHours ?? 0),
    fmt(r.regularOTHours ?? 0),
    fmt(r.regularNDHours ?? 0),
    fmt(r.regularNDOTHours ?? 0),
    fmt(r.restDayHours ?? 0),
    fmt(r.restDayOTHours ?? 0),
    fmt(r.restDayNDHours ?? 0),
    fmt(r.restDayNDOTHours ?? 0),
    fmt(r.legalHolHours ?? 0),
    fmt(r.legalHolOTHours ?? 0),
    fmt(r.legalHolNightDiffHours ?? 0),
    fmt(r.legalHolNightDiffOTHours ?? 0),
    fmt(r.specialHolHours ?? 0),
    fmt(r.specialHolOTHours ?? 0),
    fmt(r.specialHolNightDiffHours ?? 0),
    fmt(r.specialHolNightDiffOTHours ?? 0),
    fmt(r.restLegalDayHours ?? 0),
    fmt(r.restLegalDayOTHours ?? 0),
    fmt(r.restLegalDayNDHours ?? 0),
    fmt(r.restLegalDayNDOTHours ?? 0),
    fmt(r.restSpecialDayHours ?? 0),
    fmt(r.restSpecialDayOTHours ?? 0),
    fmt(r.restSpecialDayNDHours ?? 0),
    fmt(r.restSpecialDayNDOTHours ?? 0),
    fmt(r.doubleLegalHours ?? 0),
    fmt(r.doubleLegalOTHours ?? 0),
    fmt(r.doubleLegalNDHours ?? 0),
    fmt(r.doubleLegalNDOTHours ?? 0),
    fmt(r.restDoubleLegalHours ?? 0),
    fmt(r.restDoubleLegalOTHours ?? 0),
    fmt(r.restDoubleLegalNDHours ?? 0),
    fmt(r.restDoubleLegalNDOTHours ?? 0),
    fmt(r.obHours ?? 0),
    fmt(r.paidLeaveHours ?? 0),
    fmt(r.unpaidLeaveHours ?? 0),
    fmt(r.overtimeHours ?? 0),
  ]);
