export const DTR_SUMMARY_LABEL = {
  TITLE: "Daily Record Summary",
  BIO_ID: "BioId",
  EMPLOYEE: "Employee",
  // Time shift
  TIME_SHIFT: "TimeShift",
  START: "Start",
  END: "End",
  // Raw hours
  LATE: "Late",
  UNDER_TIME: "UT",
  OVER: "Over",
  OT: "OT",
  OVER_OT: "Over OT",
  ND: "ND",
  ND_OT: "ND OT",
  LH_HOURS: "LH",
  SP_HOURS: "SP",
  DAYS: "Days",
  // Rest-day hours
  RND: "RND",
  ROT: "ROT",
  RNDO: "RNDO",
  REST_DAY: "Rest Day",
  RD_ND: "RD ND",
  RD_OT: "RD OT",
  RD_NDO: "RD NDO",
  // Used hours
  LH_USED: "LH",
  SP_USED: "SP",
  // Net amounts
  REG_NET: "Reg. Net",
  NET_OT: "Net OT",
  ND_NET: "ND",
  ND_OT_NET: "ND OT",
  RD_NET: "RD Net",
  RD_OT_NET: "RD OT",
  RD_ND_OT: "RD ND OT",
  LH: "LH",
  LH_OT: "LH OT",
  LH_ND: "LH ND",
  LH_ND_OT: "LH ND OT",
  SPH: "SPH",
  SPH_OT: "SPH OT",
  SPH_ND: "SPH ND",
  SPH_ND_OT: "SPH ND OT",
  RAW_OT: "Raw OT",
  APPLIED_OT: "Applied OT",
  ABS: "ABS",
  TOTAL: "Total",
  // Filters
  FILTER_FROM_DATE: "From",
  FILTER_TO_DATE: "To",
  FILTER_DEPARTMENT: "Department",
  FILTER_CLIENT: "Client",
  FILTER_EMPLOYEE: "Employee",
  FILTER_PAYROLL_GROUP: "Payroll Group",
};
