import httpClient from "@/core/http/http-client";
import { API_PREFIX, buildApiUrl } from "@/core/http/api-url.util";
import type { AuditResponse } from "../models/api/response/audit-response.model";

const ENDPOINT = buildApiUrl(API_PREFIX.hrms, "audit-logs");

const MOCK_AUDITS: AuditResponse[] = [
  {
    id: "audit-001",
    action: "LOGIN",
    module: "Auth",
    resourceId: "user-101",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: "User logged in successfully.",
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-25T08:01:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-002",
    action: "CREATE",
    module: "Department",
    resourceId: "dept-025",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Created department "Engineering – North".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-25T08:15:22Z",
    status: "SUCCESS",
  },
  {
    id: "audit-003",
    action: "UPDATE",
    module: "Employee",
    resourceId: "emp-2045",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Updated employee profile for "Maria Santos".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-25T09:03:44Z",
    status: "SUCCESS",
  },
  {
    id: "audit-004",
    action: "DELETE",
    module: "Holiday",
    resourceId: "hol-012",
    userId: "user-102",
    userName: "Anna Reyes",
    description: 'Deleted holiday "Founding Anniversary".',
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-24T14:30:10Z",
    status: "SUCCESS",
  },
  {
    id: "audit-005",
    action: "LOGIN",
    module: "Auth",
    resourceId: "user-103",
    userId: "user-103",
    userName: "Carlos Mendoza",
    description: "Login attempt failed — invalid credentials.",
    ipAddress: "172.16.0.3",
    userAgent: "Mozilla/5.0 (Linux)",
    timestamp: "2026-05-24T11:22:05Z",
    status: "FAILED",
  },
  {
    id: "audit-006",
    action: "EXPORT",
    module: "Daily Time Record",
    resourceId: "dtr-batch-08",
    userId: "user-102",
    userName: "Anna Reyes",
    description: "Exported DTR Summary for payroll period May 2026.",
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-24T16:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-007",
    action: "APPROVE",
    module: "Change Schedule",
    resourceId: "cs-0099",
    userId: "user-104",
    userName: "Liza Santos",
    description: "Approved work rotation request for Team B.",
    ipAddress: "192.168.10.2",
    userAgent: "Mozilla/5.0 (iPhone)",
    timestamp: "2026-05-23T10:05:30Z",
    status: "SUCCESS",
  },
  {
    id: "audit-008",
    action: "REJECT",
    module: "Change Schedule",
    resourceId: "cs-0098",
    userId: "user-104",
    userName: "Liza Santos",
    description: "Rejected change rest day request — insufficient notice.",
    ipAddress: "192.168.10.2",
    userAgent: "Mozilla/5.0 (iPhone)",
    timestamp: "2026-05-23T10:12:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-009",
    action: "CREATE",
    module: "User",
    resourceId: "user-115",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Created new system user "Pedro Pascual".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-23T09:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-010",
    action: "UPDATE",
    module: "Role",
    resourceId: "role-003",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Updated permissions for role "HR Coordinator".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-23T09:45:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-011",
    action: "VIEW",
    module: "Reports",
    resourceId: "rpt-tardiness-2026-05",
    userId: "user-102",
    userName: "Anna Reyes",
    description: "Viewed tardiness report for May 2026.",
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-22T15:10:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-012",
    action: "DELETE",
    module: "User",
    resourceId: "user-113",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Deleted user account "Inactive Test User".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-22T11:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-013",
    action: "CREATE",
    module: "Payroll Group",
    resourceId: "pg-007",
    userId: "user-105",
    userName: "Mark Castillo",
    description: 'Created payroll group "Rank and File – Night Shift".',
    ipAddress: "10.10.5.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-21T08:30:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-014",
    action: "UPDATE",
    module: "Project Site",
    resourceId: "oa-004",
    userId: "user-105",
    userName: "Mark Castillo",
    description: 'Updated project site "Cavite Plant" address.',
    ipAddress: "10.10.5.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-21T09:15:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-015",
    action: "EXPORT",
    module: "Reports",
    resourceId: "rpt-export-batch-12",
    userId: "user-102",
    userName: "Anna Reyes",
    description: "Export failed — server timeout while generating report.",
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-20T17:55:00Z",
    status: "FAILED",
  },
  {
    id: "audit-016",
    action: "LOGOUT",
    module: "Auth",
    resourceId: "user-104",
    userId: "user-104",
    userName: "Liza Santos",
    description: "User session ended.",
    ipAddress: "192.168.10.2",
    userAgent: "Mozilla/5.0 (iPhone)",
    timestamp: "2026-05-20T18:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-017",
    action: "CREATE",
    module: "Time Shift",
    resourceId: "ts-fixed-010",
    userId: "user-103",
    userName: "Carlos Mendoza",
    description: 'Created fixed time shift "Morning Shift A".',
    ipAddress: "172.16.0.3",
    userAgent: "Mozilla/5.0 (Linux)",
    timestamp: "2026-05-20T10:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-018",
    action: "UPDATE",
    module: "Department",
    resourceId: "dept-003",
    userId: "user-103",
    userName: "Carlos Mendoza",
    description: 'Updated department head for "Finance".',
    ipAddress: "172.16.0.3",
    userAgent: "Mozilla/5.0 (Linux)",
    timestamp: "2026-05-19T14:22:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-019",
    action: "APPROVE",
    module: "Change Holiday",
    resourceId: "ch-0030",
    userId: "user-104",
    userName: "Liza Santos",
    description: "Approved change holiday request for Q3 2026.",
    ipAddress: "192.168.10.2",
    userAgent: "Mozilla/5.0 (iPhone)",
    timestamp: "2026-05-18T09:30:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-020",
    action: "DELETE",
    module: "Time Shift",
    resourceId: "ts-flexi-004",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Deleted flexi time shift "Old Flexi Schedule B".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-17T16:45:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-021",
    action: "CREATE",
    module: "Employee",
    resourceId: "emp-2046",
    userId: "user-105",
    userName: "Mark Castillo",
    description: 'Onboarded new employee "Rosa Aquino".',
    ipAddress: "10.10.5.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-16T08:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-022",
    action: "VIEW",
    module: "Timekeeping",
    resourceId: "tk-raw-logs-20260516",
    userId: "user-102",
    userName: "Anna Reyes",
    description: "Viewed raw attendance logs for May 16, 2026.",
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-16T09:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-023",
    action: "UPDATE",
    module: "User",
    resourceId: "user-103",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Reset password for user "Carlos Mendoza".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-15T11:30:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-024",
    action: "REJECT",
    module: "Change Holiday",
    resourceId: "ch-0028",
    userId: "user-104",
    userName: "Liza Santos",
    description:
      "Rejected change holiday request — conflicts with payroll cutoff.",
    ipAddress: "192.168.10.2",
    userAgent: "Mozilla/5.0 (iPhone)",
    timestamp: "2026-05-15T10:10:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-025",
    action: "EXPORT",
    module: "Timekeeping",
    resourceId: "tk-export-may1",
    userId: "user-105",
    userName: "Mark Castillo",
    description: "Exported attendance data for first half of May 2026.",
    ipAddress: "10.10.5.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-15T08:45:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-026",
    action: "LOGIN",
    module: "Auth",
    resourceId: "user-102",
    userId: "user-102",
    userName: "Anna Reyes",
    description: "User logged in from mobile device.",
    ipAddress: "10.0.0.55",
    userAgent: "Mozilla/5.0 (Macintosh)",
    timestamp: "2026-05-14T07:58:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-027",
    action: "DELETE",
    module: "Project Site",
    resourceId: "oa-002",
    userId: "user-103",
    userName: "Carlos Mendoza",
    description: "Delete project site failed — site has active employees.",
    ipAddress: "172.16.0.3",
    userAgent: "Mozilla/5.0 (Linux)",
    timestamp: "2026-05-13T13:00:00Z",
    status: "FAILED",
  },
  {
    id: "audit-028",
    action: "CREATE",
    module: "Role",
    resourceId: "role-006",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: 'Created new role "Payroll Processor".',
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-12T10:00:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-029",
    action: "UPDATE",
    module: "Payroll Group",
    resourceId: "pg-002",
    userId: "user-105",
    userName: "Mark Castillo",
    description: 'Updated cut-off schedule for "Supervisory" payroll group.',
    ipAddress: "10.10.5.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-11T15:20:00Z",
    status: "SUCCESS",
  },
  {
    id: "audit-030",
    action: "LOGOUT",
    module: "Auth",
    resourceId: "user-101",
    userId: "user-101",
    userName: "Juan Dela Cruz",
    description: "User session ended.",
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0)",
    timestamp: "2026-05-25T18:00:00Z",
    status: "SUCCESS",
  },
];

export const auditApi = {
  async getAll(): Promise<AuditResponse[]> {
    try {
      const data = await httpClient.getUnwrapped<AuditResponse[]>(ENDPOINT);
      return data.length ? data : MOCK_AUDITS;
    } catch {
      return MOCK_AUDITS;
    }
  },

  async getById(id: string): Promise<AuditResponse> {
    try {
      return await httpClient.getUnwrapped<AuditResponse>(`${ENDPOINT}/${id}`);
    } catch {
      const match = MOCK_AUDITS.find((item) => item.id === id);
      if (match) return match;
      throw new Error(`Audit log ${id} not found`);
    }
  },
};
