import { useMemo } from "react";
import { Button, Modal, Spin, Space, Tooltip } from "antd";
import { DownloadOutlined, CloudDownloadOutlined } from "@ant-design/icons";
import { PDFViewer, PDFDownloadLink } from "@react-pdf/renderer";
import { useEmployeeFull } from "@/app/modules/setup/employee/hooks/use-employee-queries";
import { API_PREFIX, buildApiUrl } from "@/core/http/api-url.util";
import Employee201Document from "./employee-201-document";

interface Props {
  employeeId: string;
  open: boolean;
  onClose: () => void;
}

export default function Employee201Modal({ employeeId, open, onClose }: Props) {
  const { data, isLoading } = useEmployeeFull(open ? employeeId : undefined);

  const serverPdfUrl = useMemo(() => {
    const base = buildApiUrl(API_PREFIX.hrms, "employees");
    return `${base}/${employeeId}/print-201`;
  }, [employeeId]);

  const fileName = data
    ? `201-${data.employeeNo}-${data.lastName ?? ""}.pdf`
    : "employee-201.pdf";

  return (
    <Modal
      open={open}
      onCancel={onClose}
      title={
        data ? `201 File — ${data.fullName ?? data.employeeNo}` : "201 File"
      }
      width="90vw"
      style={{ top: 16, maxWidth: 1100 }}
      styles={{ body: { padding: 0 } }}
      footer={
        <Space>
          <Button onClick={onClose}>Close</Button>
          {data && (
            <PDFDownloadLink
              document={<Employee201Document data={data} />}
              fileName={fileName}
            >
              {({ loading }) => (
                <Button
                  icon={<DownloadOutlined />}
                  loading={loading}
                  disabled={loading}
                >
                  Download (Browser)
                </Button>
              )}
            </PDFDownloadLink>
          )}
          <Tooltip title="PDF generated by the server (QuestPDF)">
            <Button
              type="primary"
              icon={<CloudDownloadOutlined />}
              href={serverPdfUrl}
              target="_blank"
              download={fileName}
            >
              Download (Server)
            </Button>
          </Tooltip>
        </Space>
      }
      destroyOnHidden
    >
      {isLoading || !data ? (
        <div
          style={{
            height: "80vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Spin tip="Loading employee data…" size="large" />
        </div>
      ) : (
        <PDFViewer
          width="100%"
          height="100%"
          style={{ height: "80vh", border: "none" }}
          showToolbar
        >
          <Employee201Document data={data} />
        </PDFViewer>
      )}
    </Modal>
  );
}
