export interface CreateLeaveType {
  code: string;
  category?: string;
  description: string;
  legalBasis: string;
  remarks: string;
  paySource: string;
  employerAdvancesPayment: boolean;
  accrualBasis: string;
  credits: number;
  accrualRate: number;
  maxAccrualBalance?: number | null;
  proRateFirstYear: boolean;
  leaveReset: string;
  minServiceMonths: number;
  genderRestriction: string;
  requiresApproval: boolean;
  requiresSupportingDocument: boolean;
  allowHalfDay: boolean;
  allowPartial: boolean;
  allowNegativeBalance: boolean;
  requiresCredits: boolean;
  maxDaysPerYear?: number | null;
  maxConsecutiveDays?: number | null;
  carryOverType: string;
  carryOverMaxDays: number;
  carryOverExpiryMonths?: number | null;
  convertToCash: boolean;
  cashConversionRate: number;
  maxCashConversionDays?: number | null;
  isStatutory: boolean;
}
