export interface LeaveMetaData {
  leaveId: string;
  name?: string;
  hours: number;
  startDateTime: string;
  endDateTime: string;
  payType: string;
}

export interface DtrDetailResponse {
  id?: string;
  batchCode?: string;
  workType: string;
  workTypeEnum: number;
  fullName?: string;
  shiftId?: string | null;
  employeeId: string;
  workDate: string;
  shiftName: string;
  shiftStartTime: string;
  shiftEndTime: string;
  startTime?: string | null;
  endTime?: string | null;
  lateMinutes: number;
  utMinutes: number;
  overMinutes: number;
  lateForOTMinutes: number;
  obHours: number;
  absentCount: number;
  holCount: number;
  spCount: number;
  paidLeaveHours: number;
  unpaidLeaveHours: number;
  leavesInfo?: LeaveMetaData[] | null;
  regularNetHours: number;
  regularOTHours: number;
  regularNDHours: number;
  regularNDOTHours: number;
  restDayHours: number;
  restDayOTHours: number;
  restDayNDHours: number;
  restDayNDOTHours: number;
  legalHolHours: number;
  legalHolOTHours: number;
  legalHolNightDiffHours: number;
  legalHolNightDiffOTHours: number;
  specialHolHours: number;
  specialHolOTHours: number;
  specialHolNightDiffHours: number;
  specialHolNightDiffOTHours: number;
  restLegalDayHours: number;
  restLegalDayOTHours: number;
  restLegalDayNDHours: number;
  restLegalDayNDOTHours: number;
  restSpecialDayHours: number;
  restSpecialDayOTHours: number;
  restSpecialDayNDHours: number;
  restSpecialDayNDOTHours: number;
  specialWorkDayHours: number;
  specialWorkDayOTHours: number;
  specialWorkDayNDHours: number;
  specialWorkDayNDOTHours: number;
  doubleLegalHours: number;
  doubleLegalOTHours: number;
  doubleLegalNDHours: number;
  doubleLegalNDOTHours: number;
  restDoubleLegalHours: number;
  restDoubleLegalOTHours: number;
  restDoubleLegalNDHours: number;
  restDoubleLegalNDOTHours: number;
  note: string;
  postingDescription?: string | null;
  userId?: string;
  branchId?: string;
  departmentId?: string;
  payrollGroupId?: string;
  clientId?: string;
  areaId?: string;
  shiftWorkingHour: number;
  posted: boolean;
  totalHours: number;
}
